version: "2"

services:

  apache:
    image: eeacms/apache:2.4-1.0
    ports:
    - "80:80"
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      SERVER_ADMIN: "helpdesk@climate-adapt-test.eea.europa.eu"
      SERVER_NAME: "climate-adapt-test.eea.europa.eu"
      RewriteRule: "^/(.*) http://plone:8080/VirtualHostBase/http/climate-adapt-test.eea.europa.eu:80/cca/VirtualHostRoot/$$1 [P,L]"
      TZ: "Europe/Copenhagen"

  plone:
    # image: 
    # build: ./devel/
    build: .
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - zeoserver
    - memcached
    environment:
      ZOPE_MODE: "zeo_client"
      TZ: "Europe/Copenhagen"
    volumes:
    - cca-downloads:/data/downloads
    - cca-plone-data:/data
    - ./src:/plone/instance/src/
    - ./buildout.cfg:/plone/instance/buildout.cfg
    ports:
      - "8190:8080"
    # command: bash -c "tail -f /dev/null"

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - "-m"
    - "2048"

  zeoserver:
    image: plone:4.3.10
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - zeoserver
    volumes:
    - cca-data:/data
    # command: bash -c "tail -f /dev/null"

  varnish:
    build: varnish/
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - apache
    environment:
      BACKENDS: "apache"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DNS_ENABLED: "true"
      BACKENDS_PORT: "80"

  # cron:
  #   build: cron/
  #   restart: always
  #   env_file:
  #   - cron/cron.env
  #   volumes:
  #   - /etc/localtime:/etc/localtime:ro

volumes:
  cca-plone-data:
  cca-async-data:
  cca-data:
  cca-downloads:
